=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/0.0.1/schemas/client_details.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/client_details.json",
  "title": "An applicant for criminal legal aid",
  "description": "Holds attributes of an applicant for legal aid; the client of a criminal legal aid provider",
  "type": "object",
  "properties": {
    "client": { "$ref": "#/definitions/person" },
    "on_remand": { "type": "boolean" },
    "other_legal_aid_cases": { "type": "string" },
    "remanded_date": { "type": "string", "format": "date" },
    "partner": { "$ref": "#/definitions/person" },
    "partner_role_in_case": { "enum": ["co-defendant", "witness", "victim", "none"] },
    "partner_conflict_of_interest": { "type": "boolean" }
  },
  "required": ["client"],
  "dependentRequired": {
    "partner": ["partner_role_in_case", "partner_conflict_of_interest"]
  },
  "definitions": {
    "person": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/general/0.0.1/schemas/person.json" }
  }
}

=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/0.0.1/examples/client_details_with_partner.json
{
    "client": {
      "first_name": "aaa",
      "last_name": "bbb",
      "address": {
        "address_line_one": "14 Real Street",
        "address_line_two": "Sometown",
        "county": "Hampshire",
        "postcode": "AB1 2CD"
      }
    },
    "partner": {
      "first_name": "ccc",
      "last_name": "bbb",
      "address": {
        "address_line_one": "14 Real Street",
        "address_line_two": "Sometown",
        "county": "Hampshire",
        "postcode": "AB1 2CD"
      }
    },
    "partner_role_in_case": "none",
    "partner_conflict_of_interest": false
}
