=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/0.0.1/schemas/laa_application.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/laa_application.json",
  "title": "An application for criminal legal aid",
  "description": "Holds attributes of a criminal legal aid application",
  "type": "object",
  "properties": {
    "client_details": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/client_details.json" },
    "case_details": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/case_details.json" },
    "interests_of_justice": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/interests_of_justice.json" },
    "means_assessment": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/means_assessment.json" },
    "evidence": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/evidence.json" }
  },
  "required": ["client_details", "case_details", "interests_of_justice", "means_assessment"],
  "allOf": [{ "$ref": "#/definitions/crown_court_conditions" }],
  "definitions": {
    "crown_court_conditions": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/0.0.1/schemas/conditions/crown_court.json" }
  }
}

=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/0.0.1/examples/laa_application.json
{
  "client_details": {
    "client": {
      "first_name": "aaa",
      "last_name": "bbb",
      "address": {
        "address_line_one": "14 Real Street",
        "address_line_two": "Sometown",
        "county": "Hampshire",
        "postcode": "AB1 2CD"
      }
    },
    "partner": {
      "first_name": "ccc",
      "last_name": "bbb",
      "address": {
        "address_line_one": "14 Real Street",
        "address_line_two": "Sometown",
        "county": "Hampshire",
        "postcode": "AB1 2CD"
      }
    },
    "partner_role_in_case": "none",
    "partner_conflict_of_interest": false
  },
  "case_details": {
    "case_type": "indictable",
    "court_type": "crown",
    "co_defendant_names": ["jill aaa", "jack aaa"],
    "offence_class": "a",
    "URN": "123abc"
  },
  "interests_of_justice": [
    "liberty",
    "livelihood"
  ],
  "means_assessment": {
    "benefits_status":   {
      "passported": true,
      "client_benefits": ["uc"],
      "partner_benefits": ["income_support"]
    },
    "total_income": 1214,
    "income": {
      "employment_status": "employed",
      "employed_income": {
        "paye": [
          {
            "paye_date": "2022-02-01",
            "paye_amount": 555,
            "paye_deductions": [
              {
                "paye_deduction_type": "ni contribution", "paye_deduction_amount": 10
              }
            ]
          }
        ]
      }
    },
    "capital": {
       "housing": [
         {
           "property_value": 123456,
           "remaining_mortgage": 1234,
           "ownership_type": "sole"
         }
       ]
    }
  },
  "evidence": [
     {
       "name": "payslip_JAN22",
       "key": "payslip_JAN22_1234.pdf",
       "description": "payslip for Jan 2022",
       "uploaded_date": "2022-02-24"
     },
     {
       "name": "payslip_FEB22",
       "key": "payslip_FEB22_1234.pdf",
       "description": "payslip for Feb 2022",
       "uploaded_date": "2022-02-24"
     },
     {
       "name": "bank_statement_JAN",
       "key": "bank_statement_JAN22_1234.pdf",
       "description": "bank statement for Feb 2022",
       "uploaded_date": "2022-02-24"
     }
   ]
}
