=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/1.0.0/schemas/means.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/1.0.0/schemas/means.json",
  "title": "Means test",
  "description": "Attributes of the means test on criminal legal aid applications",
  "type": "object",
  "properties": {
    "benefits": {
      "type": "object",
      "properties": {
        "client_benefits": { "$ref": "#/definitions/benefits" },
        "partner_benefits": { "$ref": "#/definitions/benefits" }
      }
    },
    "passporting": { "type": "boolean" },
    "total_income": { "type": "number" },
    "income": { "$ref": "#/definitions/income" },
    "outgoings": { "$ref": "#/definitions/outgoings" },
    "capital": { "$ref": "#/definitions/capital" },
    "employment_status": { "enum": ["employed", "self-employed", "none"] }
  },
  "allOf": [
    { "$ref": "#/definitions/non_passported_conditions" },
    { "$ref": "#/definitions/full_means_conditions" }
  ],
  "definitions": {
    "benefits": {
      "type": "array",
      "items": { "enum": ["income_support", "esa", "pension_credit", "jsa", "uc"] }
    },
    "income": {
      "type": "object",
      "properties": {
        "employed_income": {
          "type": "object",
          "properties": {
            "paye": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "paye_date": { "type": "string", "format": "date" },
                  "paye_amount": { "type": "number" },
                  "paye_deductions": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "paye_deduction_type": { "type": "string" },
                        "paye_deduction_amount": { "type": "number" }
                      }
                    }
                  }
                }
              }
            },
            "other_employed_income": { "type": "boolean" },
            "other_employed_income_details": { "type": "string" }
          },
          "dependentRequired": {
            "other_employed_income": ["other_employed_income_details"]
          }
        },
        "self_employed_income": {
          "type": "object",
          "properties": {
            "business_name": { "type": "string" },
            "business_address": { "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/general/0.0.1/schemas/address.json" },
            "tax_liability_last_2_years": { "type": "number" },
            "total_turnover": { "type": "number" },
            "total_drawings": { "type": "number" },
            "total_profit": { "type": "number" },
            "profit_share": { "type": "number" },
            "director_salary": { "type": "number" }
          },
          "required": ["business_name", "business_address", "total_profit", "profit_share", "director_salary"]
        },
        "other_income_sources": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "income_type": {
                "enum": [
                  "benefits",
                  "friends_family",
                  "maintenance",
                  "cash_in_hand",
                  "student",
                  "pension",
                  "rent",
                  "tax_credits",
                  "other"
                ]
              },
              "other_income_amount": { "type": "number" },
              "other_income_frequency": { "enum": ["week", "fortnight", "month", "annual"] }
            },
            "dependentRequired": {
              "income_type": ["other_income_amount", "other_income_frequency"]
            }
          }
        },
        "dependants": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "date_of_birth": { "type": "string", "format": "date" }
            }
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": { "employment_status": { "const": "employed" } },
            "required": ["employment_status"]
          },
          "then": { "required": ["employed_income"] }
        },
        {
          "if": {
            "properties": { "employment_status": { "const": "self-employed" } },
            "required": ["employment_status"]
          },
          "then": { "required": ["self_employed_income"] }
        }
      ]
    },
    "outgoings": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "outgoing_type": {
            "enum": [
              "housing",
              "council_tax",
              "childcare",
              "maintenance",
              "legal_aid"
            ]
          },
          "outgoing_amount": { "type": "number" },
          "outgoing_frequency": {
            "enum": ["week", "fortnight", "month", "annual"]
          }
        },
        "dependentRequired": {
          "outgoing_type": ["outgoing_amount", "outgoing_frequency"]
        }
      }
    },
    "capital": {
      "type": "object",
      "properties": {
        "housing": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
               "property_value": { "type": "number" },
               "remaining_mortgage": { "type": "number" },
               "ownership_type": {
                 "enum": ["with_partner", "landlord", "other_person", "sole"]
               },
               "share": { "type": "number" }
            }
          }
        },
        "vehicle": {
          "type": "object",
          "properties": {
            "vehicle_value": { "type": "number" },
            "remaining_payments": { "type": "number" },
            "purchased_over_3_years": { "type": "boolean" },
            "regular_use": { "type": "boolean" }
          }
        },
        "savings": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
               "savings_type": {
                 "enum": ["cash", "other_person_account", "certificates", "shares", "trusts", "policies"]
               },
               "savings_value": { "type": "number" },
               "savings_description": { "type": "string" }
            },
            "dependentRequired": {
              "savings_type": ["savings_value"]
            }
          }
        },
        "assets": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "asset_type": {
                "enum": ["valuable_items", "money_overseas", "timeshare", "land", "interest"]
              },
              "asset_value": { "type": "number" },
              "asset_description": { "type": "string" }
            },
            "dependentRequired": {
              "asset_type": ["asset_value"]
            }
          }
        },
        "prohibited_assets": { "type": "boolean" },
        "prohibited_description": { "type": "string" }
      },
      "dependentRequired": {
        "prohibited_assets": ["prohibited_description"]
      }
    },
    "non_passported_conditions": {
      "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/1.0.0/schemas/conditions/crown_court.json"
    },
    "full_means_conditions": {
      "$ref": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/1.0.0/schemas/conditions/full_means.json"
    }
  }
}

=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/1.0.0/examples/means.json
{
    "passporting": true,
    "benefits":   {
      "client_benefits": ["jsa"],
      "partner_benefits": ["uc"]
    },
    "employment_status": "employed",
    "total_income": 1234,
    "income": {
      "employed_income": {
        "paye": [
          {
            "paye_date": "2022-02-01",
            "paye_amount": 555,
            "paye_deductions": [
              {
                "paye_deduction_type": "ni contribution", "paye_deduction_amount": 10
              }
            ]
          }
        ]
      }
    },
    "capital": {
       "housing": [
         {
           "property_value": 123456,
           "remaining_mortgage": 1234,
           "ownership_type": "sole"
         }
        ]
    }
}
