=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/schemas/evidence.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/schemas/evidence.json",
  "title": "Evidence",
  "description": "Holds attributes for items of evidence for criminal legal aid applications",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": { "type": "string" },
      "key": { "type": "string" },
      "description": { "type": "string" },
      "uploaded_date": { "type": "string", "format": "date" }
    }
  }
}

=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/0.0.1/examples/evidence.json
[
  {
    "name": "payslip_JAN22",
    "key": "payslip_JAN22_1234.pdf",
    "description": "payslip for Jan 2022",
    "uploaded_date": "2022-02-24"
  },
  {
    "name": "payslip_FEB22",
    "key": "payslip_FEB22_1234.pdf",
    "description": "payslip for Feb 2022",
    "uploaded_date": "2022-02-24"
  },
  {
    "name": "bank_statement_JAN",
    "key": "bank_statement_JAN22_1234.pdf",
    "description": "bank statement for Feb 2022",
    "uploaded_date": "2022-02-24"
  }
]
