=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/schemas/tolerant/means_assessment.json
{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/schemas/tolerant/means_assessment.json","title":"Means test","description":"Holds attributes of the means test for criminal legal aid applications","type":"object","properties":{"benefits_status":{"$ref":"https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/schemas/tolerant/benefits_status.json"},"total_income":{"type":"number"},"income":{"$ref":"#/definitions/income"},"outgoings":{"$ref":"#/definitions/outgoings"},"capital":{"$ref":"#/definitions/capital"}},"definitions":{"income":{"type":"object","properties":{"employment_status":{"enum":["employed","self-employed","none"]},"employed_income":{"type":"object","properties":{"paye":{"$ref":"#/definitions/paye"},"other_employed_income":{"type":"boolean"},"other_employed_income_details":{"type":"string"}}},"self_employed_income":{"type":"object","properties":{"business_name":{"type":"string"},"business_address":{"$ref":"https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/general/schemas/address.json"},"tax_liability_last_2_years":{"type":"number"},"total_turnover":{"type":"number"},"total_drawings":{"type":"number"},"total_profit":{"type":"number"},"profit_share":{"type":"number"},"director_salary":{"type":"number"}}},"other_income_sources":{"type":"array","items":{"type":"object","properties":{"income_type":{"enum":["benefits","friends_family","maintenance","cash_in_hand","student","pension","rent","tax_credits","other"]},"other_income_amount":{"type":"number"},"other_income_frequency":{"enum":["week","fortnight","month","annual"]}},"dependentRequired":{"income_type":["other_income_amount","other_income_frequency"]}}},"dependants":{"type":"array","items":{"type":"object","properties":{"date_of_birth":{"type":"string","format":"date"}}}}}},"paye":{"type":"array","items":{"type":"object","properties":{"paye_date":{"type":"string","format":"date"},"paye_amount":{"type":"number"},"paye_deductions":{"type":"array","items":{"type":"object","properties":{"paye_deduction_type":{"type":"string"},"paye_deduction_amount":{"type":"number"}}}}}}},"outgoings":{"type":"array","items":{"type":"object","properties":{"outgoing_type":{"enum":["housing","council_tax","childcare","maintenance","legal_aid"]},"outgoing_amount":{"type":"number"},"outgoing_frequency":{"enum":["week","fortnight","month","annual"]}},"dependentRequired":{"outgoing_type":["outgoing_amount","outgoing_frequency"]}}},"capital":{"type":"object","properties":{"housing":{"type":"array","items":{"type":"object","properties":{"property_value":{"type":"number"},"remaining_mortgage":{"type":"number"},"ownership_type":{"enum":["with_partner","landlord","other_person","sole"]},"share":{"type":"number"}}}},"vehicle":{"type":"object","properties":{"vehicle_value":{"type":"number"},"remaining_payments":{"type":"number"},"purchased_over_3_years":{"type":"boolean"},"regular_use":{"type":"boolean"}}},"savings":{"type":"array","items":{"type":"object","properties":{"savings_type":{"enum":["cash","other_person_account","certificates","shares","trusts","policies"]},"savings_value":{"type":"number"},"savings_description":{"type":"string"}},"dependentRequired":{"savings_type":["savings_value"]}}},"assets":{"type":"array","items":{"type":"object","properties":{"asset_type":{"enum":["valuable_items","money_overseas","timeshare","land","interest"]},"asset_value":{"type":"number"},"asset_description":{"type":"string"}},"dependentRequired":{"asset_type":["asset_value"]}}},"prohibited_assets":{"type":"boolean"},"prohibited_description":{"type":"string"}}},"non_passported_conditions":{"$ref":"https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/schemas/tolerant/conditions/crown_court.json"},"full_means_conditions":{"$ref":"https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/criminal-legal-aid/schemas/tolerant/conditions/full_means.json"}}}

=== ministryofjustice/laa-schemas/prototyping/criminal-legal-aid/0.0.1/examples/means_assessment.json
{
    "benefits_status":   {
      "passported": true,
      "client_benefits": ["JSA"],
      "partner_benefits": ["income_support"]
    },
    "total_income": 1234,
    "income": {
      "employment_status": "employed",
      "employed_income": {
        "paye": [
          {
            "paye_date": "2022-02-01",
            "paye_amount": 555,
            "paye_deductions": [
              {
                "paye_deduction_type": "ni contribution", "paye_deduction_amount": 10
              }
            ]
          }
        ]
      }
    },
    "capital": {
       "housing": [
         {
           "property_value": 123456,
           "remaining_mortgage": 1234,
           "ownership_type": "sole"
         }
        ]
    }
}
